name: pharaoh_test
description: A set of examples showing effective use of Pharaoh.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh: ^0.0.6
  shelf: ^1.4.1
  shelf_enforces_ssl: ^1.2.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  spookie:
    git: 
      url: https://github.com/codekeyz/pharaoh.git
      ref: main
      path: packages/spookie